sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "8"
  - "10"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run postcodecover
branches:
  only:
    - master
# deploy:
#   provider: npm
#   email: tsevdosjohn@gmail.com
#   api_key: $NPM_API_KEY
#   on:
#     tags: true
#     repo: tsevdos/greek-in-tech
